# Generated by Django 3.1.6 on 2021-02-14 20:40

from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Previous_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Previous_date',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True, validators=[records.models.validate_date])),
                ('stat_one', models.CharField(default='99', max_length=2, validators=[records.models.validate_stat_one])),
                ('stat_two', models.CharField(default='9', max_length=1, validators=[records.models.validate_stat_two])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[records.models.validate_name])),
                ('rating', models.CharField(max_length=3, validators=[records.models.validate_rating])),
                ('score', models.IntegerField(blank=True, default=0, validators=[records.models.validate_score])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.thing')),
            ],
        ),
    ]
